/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An additional named characteristic of the resource.
 */
export type Attribute = {
  /**
   * Full creation date (ISO format).
   */
  date_created: string;
  /**
   * Full modification date (ISO format).
   */
  date_modified: string;
} & {
  /**
   * Attribute name.
   */
  name: string;
  /**
   * Attribute value.
   */
  value: string;
  /**
   * Public availability of this attribute.
   */
  visibility: "public" | "private";
};
