/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A subset of the full results array returned by the server and matching the given query.
 */
export interface ListResponse {
  /**
   * Useful resource pointers.
   */
  _links: {
    /**
     * Link to this resource.
     */
    self: {
      /**
       * A few words describing where this link points.
       */
      title: string;
      /**
       * An absolute URL of the resource.
       */
      href: string;
      /**
       * Link type (optional, value depending on the context).
       */
      type?: string;
    };
    /**
     * Link to the first resource.
     */
    first?: {
      /**
       * A few words describing where this link points.
       */
      title: string;
      /**
       * An absolute URL of the resource.
       */
      href: string;
      /**
       * Link type (optional, value depending on the context).
       */
      type?: string;
    };
    /**
     * Link to the previous resource.
     */
    prev?: {
      /**
       * A few words describing where this link points.
       */
      title: string;
      /**
       * An absolute URL of the resource.
       */
      href: string;
      /**
       * Link type (optional, value depending on the context).
       */
      type?: string;
    };
    /**
     * Link to next resource.
     */
    next?: {
      /**
       * A few words describing where this link points.
       */
      title: string;
      /**
       * An absolute URL of the resource.
       */
      href: string;
      /**
       * Link type (optional, value depending on the context).
       */
      type?: string;
    };
    /**
     * Link to last resource.
     */
    last?: {
      /**
       * A few words describing where this link points.
       */
      title: string;
      /**
       * An absolute URL of the resource.
       */
      href: string;
      /**
       * Link type (optional, value depending on the context).
       */
      type?: string;
    };
  };
  /**
   * Total number of items in the results set.
   */
  total_items: number;
  /**
   * Total number of items in this response object.
   */
  returned_items: number;
  /**
   * Expected maximum number of returned items.
   */
  limit: number;
  /**
   * The number of skipped items.
   */
  offset: number;
}
