/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TransactionTemplate {
  _embedded: {
    "fx:items": {
      name: string;
      price: number;
      quantity: number;
      quantity_min: number;
      quantity_max: number;
      weight: number;
      code: string;
      parent_code: string;
      discount_name: string;
      discount_type: string;
      discount_details: string;
      subscription_frequency: string;
      subscription_start_date: string;
      subscription_next_transaction_date: string;
      subscription_end_date: null;
      is_future_line_item: boolean;
      shipto: string;
      url: string;
      image: string;
      length: number;
      width: number;
      height: number;
      expires: number;
      date_created: null;
      date_modified: string;
    }[];
  };
  language: string;
  locale_code: string;
  use_customer_shipping_address: boolean;
  billing_first_name: string;
  billing_last_name: string;
  billing_company: string;
  billing_address1: string;
  billing_address2: string;
  billing_city: string;
  billing_state: string;
  billing_postal_code: string;
  billing_country: string;
  billing_phone: string;
  customer_email: string;
  shipping_first_name: string;
  shipping_last_name: string;
  shipping_company: string;
  shipping_address1: string;
  shipping_address2: string;
  shipping_city: string;
  shipping_state: string;
  shipping_postal_code: string;
  shipping_country: string;
  shipping_phone: string;
  total_item_price: number;
  total_tax: number;
  total_shipping: number;
  total_future_shipping: number;
  total_order: number;
  date_created: null;
  date_modified: string;
  currency_code: string;
  currency_symbol: string;
}
